# Room and Firebase load these classes through reflection during process startup.
# R8 was removing constructors in release builds, causing startup crashes before Flutter starts.
-keep class * extends androidx.room.RoomDatabase { *; }
-keep class androidx.work.impl.WorkDatabase_Impl { *; }
-keep class com.google.firebase.**Registrar { *; }
-keep class * implements com.google.firebase.components.ComponentRegistrar { *; }

# Play Integrity API — called via reflection through the integrity: dependency.
-keep class com.google.android.play.core.integrity.** { *; }
-keep class com.google.android.play.core.tasks.** { *; }

# Flutter embedding references Play Core split-install classes for deferred components,
# which this app does not use. Suppress missing-class errors generated by R8.
-dontwarn com.google.android.play.core.splitcompat.SplitCompatApplication
-dontwarn com.google.android.play.core.splitinstall.SplitInstallException
-dontwarn com.google.android.play.core.splitinstall.SplitInstallManager
-dontwarn com.google.android.play.core.splitinstall.SplitInstallManagerFactory
-dontwarn com.google.android.play.core.splitinstall.SplitInstallRequest$Builder
-dontwarn com.google.android.play.core.splitinstall.SplitInstallRequest
-dontwarn com.google.android.play.core.splitinstall.SplitInstallSessionState
-dontwarn com.google.android.play.core.splitinstall.SplitInstallStateUpdatedListener
-dontwarn com.google.android.play.core.tasks.OnFailureListener
-dontwarn com.google.android.play.core.tasks.OnSuccessListener
-dontwarn com.google.android.play.core.tasks.Task

# Kotlin metadata is read at runtime by reflection-based libraries (Gson, Retrofit, etc.).
-keepattributes *Annotation*, Signature, InnerClasses, EnclosingMethod
-keepattributes RuntimeVisibleAnnotations, RuntimeVisibleParameterAnnotations
-keep class kotlin.Metadata { *; }

# Flutter embedding and JNI entrypoints must not be renamed.
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.** { *; }
-keep class io.flutter.util.** { *; }
-keep class io.flutter.view.** { *; }
-keep class io.flutter.** { *; }
-keep class io.flutter.plugins.** { *; }

# App-specific native bridge methods (Play Integrity + Play Games MethodChannel handlers).
-keep class rs.in.dbase.kviz.MainActivity { *; }
